name: baseproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  retrofit: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/icon/
    - assets/images/image/
    - assets/images/svg/
